# Generated by Django 6.0.3 on 2026-05-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subscriber_alter_category_name_alter_dish_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('dish', 'session_key')},
        ),
    ]
