# Generated by Django 6.0.3 on 2026-05-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review_session_key_alter_review_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='session_key',
            field=models.CharField(max_length=100),
        ),
    ]
